package org.example.flowerapp.Services;

import org.example.flowerapp.Models.Enums.MaintenanceType;
import org.example.flowerapp.Models.Flower;
import org.example.flowerapp.Models.Maintenance;
import org.example.flowerapp.Repository.FlowerRepository;
import org.example.flowerapp.Repository.MaintenanceRepository;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ManualMaintenanceServiceTest {

    @Mock
    private MaintenanceRepository maintenanceRepository;

    @Mock
    private FlowerRepository flowerRepository;

    @InjectMocks
    private ManualMaintenanceService service;

    @Test
    void shouldCreateManualTask() {
        // Given
        Flower flower = new Flower();
        flower.setFlower_id(1L);
        flower.setFlowerName("Rose");

        when(flowerRepository.findByFlowerId(1L)).thenReturn(flower);
        when(maintenanceRepository.save(any(Maintenance.class))).thenAnswer(i -> i.getArguments()[0]);

        // When
        Maintenance result = service.createManualTask(
                1L,
                MaintenanceType.WATERING,
                LocalDateTime.now().plusDays(1),
                "Custom notes"
        );

        // Then
        assertNotNull(result);
        assertFalse(result.isAutoGenerated());
        assertFalse(result.isCompleted());
        assertEquals("Custom notes", result.getNotes());
        verify(maintenanceRepository, times(1)).save(any(Maintenance.class));
    }

    @Test
    void shouldToggleAutoSchedulingOn() {
        // Given
        Flower flower = new Flower();
        flower.setFlower_id(1L);
        flower.setAutoScheduling(false);

        when(flowerRepository.findByFlowerId(1L)).thenReturn(flower);

        // When
        service.toggleAutoScheduling(1L, true);

        // Then
        assertTrue(flower.isAutoScheduling());
        verify(flowerRepository, times(1)).save(flower);
    }

    @Test
    void shouldToggleAutoSchedulingOff() {
        // Given
        Flower flower = new Flower();
        flower.setFlower_id(1L);
        flower.setAutoScheduling(true);

        when(flowerRepository.findByFlowerId(1L)).thenReturn(flower);

        // When
        service.toggleAutoScheduling(1L, false);

        // Then
        assertFalse(flower.isAutoScheduling());
        verify(flowerRepository, times(1)).save(flower);
    }

    @Test
    void shouldRescheduleTask() {
        // Given
        Maintenance task = new Maintenance();
        task.setTask_id(1L);
        task.setScheduledDate(LocalDateTime.now());

        LocalDateTime newDate = LocalDateTime.now().plusDays(3);
        when(maintenanceRepository.findByTaskId(1L)).thenReturn(task);

        // When
        service.rescheduleTask(1L, newDate);

        // Then
        assertEquals(newDate, task.getScheduledDate());
        verify(maintenanceRepository, times(1)).save(task);
    }

    @Test
    void shouldDeleteTask() {
        // Given
        when(maintenanceRepository.deleteMaintenance(1L)).thenReturn(true);

        // When
        service.deleteTask(1L);

        // Then
        verify(maintenanceRepository, times(1)).deleteMaintenance(1L);
    }
}