package org.example.flowerapp.Services;

import com.jayway.jsonpath.internal.function.sequence.Last;
import org.example.flowerapp.Models.Enums.FlowerColor;
import org.example.flowerapp.Models.Enums.MaintenanceType;
import org.example.flowerapp.Models.Flower;
import org.example.flowerapp.Models.Maintenance;
import org.example.flowerapp.Repository.FlowerRepository;
import org.example.flowerapp.Repository.MaintenanceRepository;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
class FlowerMaintenanceSchedulerIntegrationTest {

    @Autowired
    private FlowerMaintenanceScheduler scheduler;

    @Autowired
    private FlowerRepository flowerRepository;

    @Autowired
    private MaintenanceRepository maintenanceRepository;

    @AfterEach
    void cleanup() {
        // Clean up test data
        List<Maintenance> allMaintenance = maintenanceRepository.findAllMaintenance();
        for (Maintenance m : allMaintenance) {
            maintenanceRepository.deleteMaintenance(m.getTask_id());
        }

        List<Flower> allFlowers = flowerRepository.findAllFlower();
        for (Flower f : allFlowers) {
            flowerRepository.deleteFlower(f.getFlower_id());
        }
    }

    @Test
    void endToEndSchedulingTest() {
        // Given: Create a flower that needs watering
        Flower rose = new Flower();
        rose.setFlowerName("Test Rose");
        rose.setSpecies("Rosa");
        rose.setColor(FlowerColor.RED);
        rose.setPlantingDate(LocalDateTime.now().minusDays(10));
        rose.setGridPosition(1);
        rose.setWaterFrequencyDays(2);
        rose.setLastWateredDate(LocalDateTime.now().minusDays(3)); // 3 days ago - OVERDUE!
        rose.setAutoScheduling(true);

        Flower savedFlower = flowerRepository.save(rose);

        System.out.println("Created flower with ID: " + savedFlower.getFlower_id());
        System.out.println("Water frequency: " + savedFlower.getWaterFrequencyDays());
        System.out.println("Last watered: " + savedFlower.getLastWateredDate());
        System.out.println("Auto-schedule enabled: " + savedFlower.isAutoScheduling());

        // When: Run the scheduler
        scheduler.scheduleMaintenanceTasks();

        // Then: Task should be created
        List<Maintenance> tasks = maintenanceRepository.findByFlowerId(savedFlower.getFlower_id());

        System.out.println("Number of tasks created: " + tasks.size());
        if (!tasks.isEmpty()) {
            System.out.println("Task type: " + tasks.get(0).getTaskType());
        }

        assertEquals(1, tasks.size(), "Should create exactly one task");
        Maintenance task = tasks.get(0);
        assertEquals(MaintenanceType.WATERING, task.getTaskType());
        assertTrue(task.isAutoGenerated());
        assertFalse(task.isCompleted());
    }

    @Test
    void shouldNotCreateDuplicateOnSecondRun() {
        // Given: Flower that needs watering
        Flower rose = new Flower();
        rose.setFlowerName("Test Rose");
        rose.setSpecies("Rosa");
        rose.setColor(FlowerColor.RED);
        rose.setPlantingDate(LocalDateTime.now().minusDays(10));
        rose.setGridPosition(1);
        rose.setWaterFrequencyDays(2);
        rose.setLastWateredDate(LocalDateTime.now().minusDays(3));
        rose.setAutoScheduling(true);

        Flower savedFlower = flowerRepository.save(rose);

        // When: Run scheduler twice
        scheduler.scheduleMaintenanceTasks();
        scheduler.scheduleMaintenanceTasks();

        // Then: Still only one task
        List<Maintenance> tasks = maintenanceRepository.findByFlowerId(savedFlower.getFlower_id());
        assertEquals(1, tasks.size(), "Should not create duplicate tasks");
    }

    @Test
    void shouldNotCreateTaskWhenAutoScheduleDisabled() {
        // Given: Flower with auto-schedule disabled
        Flower rose = new Flower();
        rose.setFlowerName("Manual Rose");
        rose.setSpecies("Rosa");
        rose.setColor(FlowerColor.YELLOW);
        rose.setPlantingDate(LocalDateTime.now().minusDays(10));
        rose.setGridPosition(2);
        rose.setWaterFrequencyDays(2);
        rose.setLastWateredDate(LocalDateTime.now().minusDays(5));
        rose.setAutoScheduling(false); // Disabled!

        Flower savedFlower = flowerRepository.save(rose);

        // When: Run scheduler
        scheduler.scheduleMaintenanceTasks();

        // Then: No tasks created
        List<Maintenance> tasks = maintenanceRepository.findByFlowerId(savedFlower.getFlower_id());
        assertEquals(0, tasks.size(), "Should not create task when auto-schedule is disabled");
    }
}