package org.example.flowerapp.Services;

import org.apache.catalina.User;
import org.aspectj.lang.annotation.After;
import org.aspectj.lang.annotation.Before;
import org.example.flowerapp.Models.Enums.MaintenanceType;
import org.example.flowerapp.Models.Flower;
import org.example.flowerapp.Models.Maintenance;
import org.example.flowerapp.Repository.FlowerRepository;
import org.example.flowerapp.Repository.MaintenanceRepository;
import org.hibernate.sql.Delete;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.scheduling.config.Task;
import org.springframework.stereotype.Service;
import reactor.core.scheduler.Scheduler;

import java.time.LocalDateTime;

@Service
public class ManualMaintenanceService {
    private final MaintenanceRepository maintenanceRepository;
    private final FlowerRepository flowerRepository;

    public ManualMaintenanceService(FlowerRepository flowerRepository, MaintenanceRepository maintenanceRepository) {
        this.flowerRepository = flowerRepository;
        this.maintenanceRepository = maintenanceRepository;
    }

    // User creates a custom task manually
    public Maintenance createManualTask(long flowerId, String userId, MaintenanceType type,
                                        LocalDateTime scheduledDate, String notes) {
        Flower flower = flowerRepository.findByFlowerIdAndUserId(flowerId, userId);

        Maintenance task = new Maintenance();
        task.setFlower(flower);
        task.setUserId(userId);  // Set userId
        task.setTaskType(type);
        task.setScheduledDate(scheduledDate);
        task.setAutoGenerated(false);  // Mark as MANUAL
        task.setCompleted(false);
        task.setCreatedAt(LocalDateTime.now());
        task.setNotes(notes != null ? notes : "Manual task");

        return maintenanceRepository.save(task);
    }

    // User toggles auto-scheduling on/off
    public void toggleAutoScheduling(long flowerId, String userId, boolean enabled) {
        Flower flower = flowerRepository.findByFlowerIdAndUserId(flowerId, userId);
        flower.setAutoScheduling(enabled);
        flowerRepository.save(flower);
    }

    // User edits an existing task
    public void rescheduleTask(long taskId, String userId, LocalDateTime newDate) {
        Maintenance task = maintenanceRepository.findByTaskIdAndUserId(taskId, userId);
        task.setScheduledDate(newDate);
        maintenanceRepository.save(task);
    }

    // User deletes a task they don't want
    public void deleteTask(long taskId, String userId) {
        maintenanceRepository.deleteMaintenance(taskId, userId);
    }
}